### ISSUE TITLE
ccm create dse - HTTP Error 401: basic auth failed

### ISSUE THREAD

**Issue by dins2k2** [riptano/ccm#531]
Trying to create a new cluster with DSE version 4.8.0 and OpsCenter 5.2, getting below error.

`ccm create --dse -v 4.8.0 --dse-username=DSEemail --dse-password=DSEpass -o 5.2 -n 2:1 dse48`

> Traceback (most recent call last):
>   File "/usr/local/bin/ccm", line 5, in <module>
>     pkg_resources.run_script('ccm==2.1.7', 'ccm')
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/local/lib/python2.7/dist-packages/ccm-2.1.7-py2.7.egg/EGG-INFO/scripts/ccm", line 86, in <module>
> 
>   File "build/bdist.linux-x86_64/egg/ccmlib/cmds/cluster_cmds.py", line 156, in run
>   File "build/bdist.linux-x86_64/egg/ccmlib/dse_cluster.py", line 31, in **init**
>   File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 63, in **init**
>   File "build/bdist.linux-x86_64/egg/ccmlib/dse_cluster.py", line 38, in load_from_repository
>   File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 87, in setup_dse
>   File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 229, in download_dse_version
> ccmlib.common.ArgumentError: Invalid url http://downloads.datastax.com/enterprise/dse-4.8.0-bin.tar.gz (underlying error is: HTTP Error 401: basic auth failed)

Am I missing anything here? I'm able to download manually the DSE 4.8.0 using above URL with DSE credentials. 

**Ubuntu 14.10, Python 2.7**

Thanks,
Dinesh

**Comment by bcantoni** [comment]
@dins2k2 are you still having this problem or did you resolve it? I was able to use your `ccm create` command and it worked correctly. One thing to watch out for is any special characters in your DSE username or password which might need to be escaped on the command line.

Another alternative is to drop your credentials in a file `~/.ccm/.dse.ini` which looks like:
```
[dse_credentials]
dse_username=YOUR-USERNAME
dse_password=YOUR-PASSWORD
```

**Comment by dins2k2** [comment]
@bcantoni Thanks for making this thread live again. I did take care of the special characters. I think it happens only in my office laptop. Looks like some system or enterprise firewall is blocking it. I can able to connect and create dse clusters in my personal laptop.

Again thanks for the **DSE_CREDENTIALS_FILE** approach for creating the clusters.
