### ISSUE TITLE
Running multi-clusters via ccm?

### ISSUE THREAD

**Issue by fosholaw** [riptano/ccm#674]
I want experiment Multi-Cluster setup. Is there a way to do that in ccm?

**Comment by ptnapoleon** [comment]
Yes, as long as only one cluster is live at once. Use `ccm list` and `ccm switch` commands to switch between clusters, and `ccm start` and `ccm stop` to manage their lifecycle

**Comment by fosholaw** [comment]
Thanks @ptnapoleon.

But could we create an issue/ticket to add support for allowing multiple live clusters running at the same time?

**Comment by ptnapoleon** [comment]
No. The database doesn't support that, and so I'm not going to try to. If you need that kind of set up, you'll want real virtualization, or something else more complicated than ccm.
