### ISSUE TITLE
AssertionError: Could not do a git clone

### ISSUE THREAD

**Issue by Suryakumar007** [riptano/ccm#701]
When i execute this command, `ccm create test -v 3.11 -n 3 -s`, Error throws up. It reads as 
"ccm WARNING Downloading 3.11.4 failed, trying to build from git instead.
The error was: Invalid version 3.11.4 (underlying error is: <urlopen error [Errno 110] Connection timed out>)
http://git.apache.org/cassandra.git git:cassandra-3.11"

**Comment by dins2k2** [comment]
Suryakumar,

Per this [C* dist archive](http://archive.apache.org/dist/cassandra/), there is no C* version called 3.11. All I see is below C* versions with respect to 3.11.*...

3.11.0, 3.11.1, 3.11.2, 3.11.3 & 3.11.4 

May be you should try the below ccm create command by mentioning the correct version of C* version for your requirement.

ccm create test -v 3.11.4 -n 3 -s

HTH.

Thanks,
Dinesh

**Comment by Suryakumar007** [comment]
Hi dinesh,

Thank you so much. Yes I have tried 3.11.4 previously and after it too failed I put 3.11.

But now I tried to execute that it got worked. Don't know how it did not worked before and worked now. Anyhow it worked.. :) 

Thanks for the response.
Suryakumar.
